# Generated by Django 4.1.5 on 2023-05-23 04:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('lot', models.IntegerField()),
                ('plan', models.CharField(max_length=64)),
                ('tenure', models.CharField(max_length=64)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='LandParcelHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_json', models.JSONField()),
                ('json', models.JSONField()),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandParcelOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('bulk_mail_target', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('preferred_name', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Undisclosed'), ('N', 'N/A')], default='N', max_length=1)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('date_ownership_start', models.DateField(blank=True, null=True)),
                ('date_ownership_ceased', models.DateField(blank=True, null=True)),
                ('address_street', models.CharField(blank=True, max_length=512, null=True)),
                ('address_postal', models.CharField(blank=True, max_length=512, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('contact_mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('contact_fax', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ['parcel', '-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='LandParcelOwnerCorrespondence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['owner', '-date_updated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandParcelOwnerHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('modified_json', models.JSONField()),
                ('json', models.JSONField()),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandParcelOwnerNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=512)),
            ],
            options={
                'ordering': ['owner', '-date_updated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandParcelOwnerReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=512)),
                ('date_due', models.DateField()),
            ],
            options={
                'ordering': ['owner', '-date_updated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandParcelOwnerTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('N', 'Not Started'), ('I', 'In Progress'), ('R', 'Review'), ('C', 'Completed')], max_length=1)),
                ('priority', models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High'), (5, 'Immediate')])),
                ('date_due', models.DateField()),
            ],
            options={
                'ordering': ['owner', '-date_updated'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandParcelProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('files', models.ManyToManyField(blank=True, related_name='land_parcel_files', to='media_file.mediafile')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_projects', to='lms.landparcel')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
