# Generated by Django 4.1.5 on 2023-05-23 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_file', '0001_initial'),
        ('lms', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='landparcelproject',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownertask',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_files', to='media_file.mediafile'),
        ),
        migrations.AddField(
            model_name='landparcelownertask',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lms.landparcelowner'),
        ),
        migrations.AddField(
            model_name='landparcelownertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownertask',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownerreminder',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_files', to='media_file.mediafile'),
        ),
        migrations.AddField(
            model_name='landparcelownerreminder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='lms.landparcelowner'),
        ),
        migrations.AddField(
            model_name='landparcelownerreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownerreminder',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownernote',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_files', to='media_file.mediafile'),
        ),
        migrations.AddField(
            model_name='landparcelownernote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='lms.landparcelowner'),
        ),
        migrations.AddField(
            model_name='landparcelownernote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownernote',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownerhistory',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='lms.landparcelowner'),
        ),
        migrations.AddField(
            model_name='landparcelownerhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownercorrespondence',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_files', to='media_file.mediafile'),
        ),
        migrations.AddField(
            model_name='landparcelownercorrespondence',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='lms.landparcelowner'),
        ),
        migrations.AddField(
            model_name='landparcelownercorrespondence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelownercorrespondence',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelowner',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='land_parcel_owner_files', to='media_file.mediafile'),
        ),
        migrations.AddField(
            model_name='landparcelowner',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='lms.landparcelproject'),
        ),
        migrations.AddField(
            model_name='landparcelowner',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_land_parcel_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelowner',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_land_parcel_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcelhistory',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='lms.landparcelproject'),
        ),
        migrations.AddField(
            model_name='landparcelhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='landparcelproject',
            unique_together={('project', 'parcel')},
        ),
        migrations.AddConstraint(
            model_name='landparcelowner',
            constraint=models.UniqueConstraint(condition=models.Q(('bulk_mail_target', True)), fields=('parcel', 'bulk_mail_target'), name='unique_bulk_mail_target_field', violation_error_message='There can only be one bulk mail target per parcel.'),
        ),
        migrations.AddConstraint(
            model_name='landparcelowner',
            constraint=models.CheckConstraint(check=models.Q(('bulk_mail_target', True), models.Q(('bulk_mail_target', True), _negated=True), _connector='OR'), name='valid_bulk_mail_target', violation_error_message='The bulk mail target field must be True or False.'),
        ),
    ]
