# Generated by Django 4.1.5 on 2023-08-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='segment_parcel',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Segment Parcel'),
        ),
    ]
